extends SequenceEvent

func trigger() -> void:
	use_highlight_tool(toys[0].intervals[0])
	await delay(0.2)
	use_highlight_tool(toys[0].intervals[1])
	await delay(0.2)
	use_highlight_tool(toys[0].intervals[2])
	await delay(0.5)
	use_highlight_tool(toys[1].intervals[0])
	await delay(0.2)
	use_highlight_tool(toys[1].intervals[1])
	await delay(0.2)
	use_highlight_tool(toys[1].intervals[2])
	await delay(0.2)
	use_highlight_tool(toys[1].intervals[3])
	await delay(0.5)
	use_highlight_tool(toys[2].intervals[0])
	await delay(0.2)
	use_highlight_tool(toys[2].intervals[1])
	await delay(0.2)
	use_highlight_tool(toys[2].intervals[2])
	await delay(0.2)
	use_highlight_tool(toys[2].intervals[3])
	await delay(0.2)
	use_highlight_tool(toys[2].intervals[4])
	await delay(0.2)
	use_highlight_tool(toys[2].intervals[5])
	await delay(0.5)
	clear_highlighted(toys[0])
	clear_highlighted(toys[1])
	clear_highlighted(toys[2])
